# Generated by Django 4.1.4 on 2022-12-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.TextField(max_length=64, unique=True),
        ),
    ]
